### PR TITLE
Add DueDateStatus

### PR DESCRIPTION
**Pull request by MPuls-actano**
This adds and exports the `DueDateStatus` react component and a constant `DUE_DATE_STATUS`. The representation in the storybook is also included.

Only small changes in comparison to the original implementation in https://github.com/actano/rplan-planning-objects-webclient/blob/master/src/project-page/components/header-bar/components/due-date-status.jsx were made - particularly values and location for `DUE_DATE_STATUS`

`DUE_DATE_STATUS` contains the possible values for the prop `state` of the `DueDateStatus` react component

### CODE REVIEW

**Comment by MPuls-actano** [comment]
I can do the versioning of `rplan-corporate-design` after the merge.

**Comment by hpurmann** [comment]
Who feels entitled to review this? i.e. who "owns" this repo? @ChristophVitz-Actano your team?

**Comment by ChristophVitz-Actano** [comment]
Yes, we talked to team saturn and we'll review it 👍

**Comment by MPuls-actano** [comment]
I will have another look into it, since I've seen, that the back-end API can response with an `inapplicable` and `at risk` status for the project health. I had removed the handling for these status and will insert them again.

**Comment by MPuls-actano** [comment]
Done.

**Comment by leosmac** [comment]
We're reviewing internally in the team Saturn, since we'd be blocked otherwise.

**Comment by leosmac** [comment]
We're still not merging without the repository owner's permission though, whoever that is.

**Comment by ChristophVitz-Actano** [comment]
I'll review it in detail later - but looks very good on first glance. Merged, so you aren't blocked

**Pull request merged**
